spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      #group.id is required when group management is used
      group-id: group_id
      auto-offset-reset: earliest
      # StringDeserializer is the default
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer