spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      # StringDeserializer is the default
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

